import {
    Package4,
    k2BaseCamp1,
    deosaiTrek,
    nangaParbat,
    MosesPeak,
    LakebaraBroq,
    fairyMeadowsTrek1,
    fairyMeadowsTrek2
} from "@/app/index";
export const treks = [{
        id: "k2-base-camp",
        slug: "k2-base-camp",
        title: "K2 Base Camp",
        subtitle: "The Savage Mountain's Gateway",
        difficulty: "Extreme",
        duration: "14-16 days",
        elevation: "5,150m",
        description: "Standing at the foot of K2, the world's second-highest peak, is an experience that defies description. The trek to K2 Base Camp is not just a journey through some of the most spectacular mountain scenery on Earth—it's a pilgrimage to one of mountaineering's most sacred sites.",
        mainImage: k2BaseCamp1,
        secondaryImage: Package4,
        highlights: [{
                title: "Concordia",
                description: "Known as the 'Throne Room of the Mountain Gods,' where four 8,000m peaks converge",
            },
            {
                title: "Baltoro Glacier",
                description: "One of the longest glaciers outside the polar regions",
            },
            {
                title: "Gasherbrum Base Camp",
                description: "Views of multiple 8,000m peaks including Gasherbrum I and II",
            },
            {
                title: "Broad Peak Base Camp",
                description: "Close-up views of the 12th highest mountain in the world",
            },
        ],
        bestTimeToVisit: "The optimal trekking season is from June to September, with July and August offering the most stable weather conditions. However, be prepared for extreme weather changes and challenging terrain regardless of the season.",
        content: "The K2 Base Camp trek is considered one of the most challenging non-technical treks in the world. Starting from Skardu, you'll traverse the legendary Baltoro Glacier, walking in the footsteps of legendary mountaineers who have attempted to conquer the 'Savage Mountain.'\n\nThe journey begins with a scenic drive from Skardu to Askole, the last village before entering the wilderness. From there, you'll trek through varied terrain, from lush valleys to barren moraines, as you make your way up the Baltoro Glacier.\n\nAs you ascend, the views become increasingly dramatic, with towering peaks like Masherbrum, Trango Towers, and Mitre Peak dominating the skyline. The highlight of the trek is reaching Concordia, where K2, Broad Peak, and the Gasherbrums create a 360-degree panorama of mountaineering glory.\n\nThe final push to K2 Base Camp takes you across challenging glacier terrain, but the reward is standing in the shadow of the world's second-highest mountain, a place few people ever get to experience.\n\nThis trek requires excellent physical fitness, prior high-altitude experience, and mental fortitude. The remoteness of the area means medical facilities are limited, and evacuation can be difficult. However, for those prepared for the challenge, the K2 Base Camp trek offers an unparalleled adventure in one of the world's most spectacular mountain environments.",
    },
    {
        id: "deosai-national-park",
        slug: "deosai-national-park",
        title: "Deosai National Park",
        subtitle: "Land of Giants",
        difficulty: "Moderate",
        duration: "3-5 days",
        elevation: "4,114m",
        description: "Deosai National Park, literally meaning 'Land of Giants,' is the second-highest plateau in the world and one of Pakistan's most unique ecosystems. This vast expanse of rolling hills, pristine lakes, and colorful wildflowers offers a completely different trekking experience from the rocky peaks of the Karakoram.",
        mainImage: deosaiTrek,
        secondaryImage: deosaiTrek,
        highlights: [{
                title: "Sheosar Lake",
                description: "A pristine alpine lake surrounded by wildflower meadows",
            },
            {
                title: "Bara Pani",
                description: "Crystal-clear springs emerging from underground sources",
            },
            {
                title: "Kala Pani",
                description: "Dark waters contrasting beautifully with golden grasslands",
            },
            {
                title: "Wildflower Blooms",
                description: "Spectacular displays of alpine flowers from July to August",
            },
        ],
        bestTimeToVisit: "The best time to visit Deosai is from June to September when the snow has melted and the plateau is accessible. July and August are particularly beautiful when the wildflowers are in full bloom.",
        content: "Deosai National Park offers a completely different experience from the towering peaks of the Karakoram. This vast plateau, situated at an average elevation of 4,114 meters, stretches over 3,000 square kilometers of pristine wilderness.\n\nThe journey to Deosai typically begins from Skardu, with a scenic drive through mountain valleys before ascending to the plateau. Once on the plateau, visitors are greeted by an endless expanse of rolling hills covered in wildflowers during the summer months.\n\nDeosai is home to the endangered Himalayan brown bear, along with snow leopards, ibex, and over 124 species of birds. The park's isolation and protection have created a haven for wildlife that's rarely seen elsewhere in Pakistan.\n\nThe crown jewel of Deosai is Sheosar Lake, a crystal-clear alpine lake surrounded by meadows and mountains. The reflection of clouds and surrounding peaks in its still waters creates a mesmerizing sight that photographers dream of capturing.\n\nUnlike many treks in Pakistan, exploring Deosai doesn't require technical climbing skills or extreme fitness. The relatively flat terrain makes it accessible to a wider range of visitors, though the high altitude still demands proper acclimatization.\n\nCamping on the plateau under the star-filled sky is an unforgettable experience. The absence of light pollution makes Deosai one of the best places in Pakistan for stargazing, with the Milky Way clearly visible on clear nights.\n\nWhether you're a wildlife enthusiast, photographer, or simply seeking tranquility in nature, Deosai National Park offers a unique adventure in one of Pakistan's most pristine environments.",
    },
    {
        id: "nanga-parbat-basecamp",
        slug: "nanga-parbat-basecamp",
        title: "Nanga Parbat Base Camp",
        subtitle: "The Killer Mountain's Threshold",
        difficulty: "Hard",
        duration: "12-14 days",
        elevation: "3,850m",
        description: "Nanga Parbat, the 'Killer Mountain,' earned its ominous nickname from the numerous early attempts that ended in tragedy. Today, the trek to its base camp offers adventurers a chance to witness the massive Rupal Face—the largest mountain face in the world—while experiencing the rich culture of the Diamir Valley.",
        mainImage: nangaParbat,
        secondaryImage: nangaParbat,
        highlights: [{
                title: "The Rupal Face",
                description: "The largest mountain face on Earth, rising 4,600 meters from base to summit",
            },
            {
                title: "Tarashing Village",
                description: "Traditional mountain village with terraced fields",
            },
            {
                title: "Shaigiri",
                description: "Last permanent settlement before entering the wilderness",
            },
            {
                title: "Local Culture",
                description: "Experience the legendary warmth of mountain communities",
            },
        ],
        bestTimeToVisit: "The best time to trek to Nanga Parbat Base Camp is from June to September, with July and August offering the most stable weather conditions.",
        content: "The trek to Nanga Parbat Base Camp is a journey to the foot of the world's ninth-highest mountain, a peak notorious for its difficulty and deadly history. The mountain's name translates to 'Naked Mountain' in Urdu, referring to its exposed, steep slopes that are often free of snow.\n\nThere are two main routes to approach Nanga Parbat: the Diamir Face route from Chilas and the Rupal Face route from Tarashing. The Rupal Face route is particularly spectacular, taking trekkers to the base of the largest mountain face on Earth, rising an incredible 4,600 meters from base to summit.\n\nThe journey begins in the lush Rupal Valley, passing through traditional villages where life continues much as it has for centuries. Trekkers have the opportunity to experience local culture and hospitality before entering the wilderness.\n\nAs you ascend, the vegetation gradually gives way to rocky terrain and glacial moraines. The trail crosses streams fed by glacial meltwater and traverses alpine meadows that burst with wildflowers during the summer months.\n\nReaching Herrligkoffer Base Camp (named after the German expedition leader) rewards trekkers with an awe-inspiring view of the Rupal Face. Standing beneath this colossal wall of rock and ice puts human ambition into perspective and helps explain why Nanga Parbat has challenged mountaineers for generations.\n\nThe trek involves crossing glacial moraines, navigating loose scree slopes, and dealing with rapidly changing weather conditions. Proper acclimatization and physical fitness are essential for this challenging journey.\n\nFor those with additional time and energy, a side trip to Shaigiri Peak offers panoramic views of Nanga Parbat and the surrounding mountains, including distant glimpses of the Karakoram range.",
    },
    {
        id: "moses-peak",
        slug: "moses-peak",
        title: "Moses Peak",
        subtitle: "Hidden Gem of Karakoram",
        difficulty: "Hard",
        duration: "8-10 days",
        elevation: "4,200m",
        description: "Moses Peak remains one of the lesser-known gems in the Karakoram range, offering intrepid trekkers a chance to experience pristine wilderness without the crowds found on more popular routes. This challenging trek rewards adventurers with spectacular views and a true sense of exploration.",
        mainImage: MosesPeak,
        secondaryImage: LakebaraBroq,
        highlights: [{
                title: "Pristine Glaciers",
                description: "Untouched ice formations and crevasse fields",
            },
            {
                title: "Technical Sections",
                description: "Challenging rock scrambles and glacier crossings",
            },
            {
                title: "360° Views",
                description: "Panoramic vistas of the central Karakoram",
            },
            {
                title: "Wildlife Encounters",
                description: "Opportunities to spot blue sheep and snow leopards",
            },
        ],
        bestTimeToVisit: "The best time to trek to Moses Peak is from June to September, with July and August offering the most stable weather conditions.",
        content: "Moses Peak, standing at approximately 5,770 meters, remains one of the lesser-known gems in the Karakoram range. This relative obscurity offers intrepid trekkers a chance to experience pristine wilderness without the crowds found on more popular routes.\n\nThe journey to Moses Peak typically begins from the Hushe Valley, a region known for its traditional villages and agricultural terraces. The initial days of trekking take you through apricot orchards and wheat fields, offering glimpses into the sustainable mountain lifestyle that has persisted for generations.\n\nAs you ascend, the trail becomes increasingly challenging, with river crossings, boulder fields, and steep ascents. The landscape transforms from green valleys to rocky moraines and eventually to the glacial world that characterizes the high Karakoram.\n\nOne of the highlights of this trek is the opportunity to witness untouched glaciers with their fascinating ice formations, seracs, and crevasses. Unlike more frequented areas, these glaciers show minimal signs of human impact.\n\nThe base camp area offers spectacular views of surrounding peaks, including glimpses of K7 and the Charakusa Valley peaks. On clear days, the panorama extends to include some of the most impressive mountains in the Karakoram range.\n\nFor those with mountaineering experience, there are opportunities for further exploration, including high camps and viewpoints that offer even more dramatic perspectives of this remote mountain wilderness.\n\nThe trek requires excellent physical condition, previous high-altitude experience, and proper technical equipment. The remote location means self-sufficiency and careful planning are absolutely essential.\n\nHowever, for those seeking an authentic wilderness experience away from established trekking routes, Moses Peak offers a genuine adventure in one of the world's most spectacular mountain ranges.",
    },
    {
        id: "fairy-meadows",
        slug: "fairy-meadows",
        title: "Fairy Meadows",
        subtitle: "Heaven on Earth",
        difficulty: "Easy to Moderate",
        duration: "4-6 days",
        elevation: "3,300m",
        description: "Fairy Meadows truly lives up to its magical name. This enchanting alpine meadow, nestled at the base of Nanga Parbat, offers one of the most accessible yet spectacular mountain experiences in Pakistan. The contrast between lush green meadows and the towering ice-covered peak creates a scene of unparalleled beauty.",
        mainImage: fairyMeadowsTrek1,
        secondaryImage: fairyMeadowsTrek2,
        highlights: [{
                title: "Alpine Meadows",
                description: "Carpets of wildflowers during summer months",
            },
            {
                title: "Nanga Parbat Views",
                description: "Unobstructed views of the ninth highest peak",
            },
            {
                title: "Beyal Camp",
                description: "Higher camp with even more dramatic mountain vistas",
            },
            {
                title: "Raikot Glacier",
                description: "Easy access to glacier viewing points",
            },
        ],
        bestTimeToVisit: "The best time to visit Fairy Meadows is from May to October, with June to September offering the most pleasant weather and lush green meadows.",
        content: "Fairy Meadows truly lives up to its magical name. This enchanting alpine meadow, nestled at the base of Nanga Parbat, offers one of the most accessible yet spectacular mountain experiences in Pakistan.\n\nThe journey begins with a drive from Raikot Bridge on the Karakoram Highway to Tato village. From there, visitors take a thrilling jeep ride up a narrow mountain road, often described as one of the most dangerous roads in the world. The final leg is a moderate 3-4 hour trek through pine forests to reach the meadows.\n\nUpon arriving at Fairy Meadows, visitors are rewarded with breathtaking views of Nanga Parbat's Raikot Face. The contrast between lush green meadows in the foreground and the towering ice-covered peak creates a scene of unparalleled beauty that has captivated photographers and nature lovers for generations.\n\nAccommodation options range from basic camping to comfortable wooden cabins, making this destination suitable for a wide range of travelers. The area has developed some tourism infrastructure while still maintaining its natural charm.\n\nFor those seeking more adventure, a day hike to Beyal Camp brings you even closer to Nanga Parbat, with increasingly dramatic views of the mountain and the Raikot Glacier. More ambitious hikers can continue to the viewpoint for Nanga Parbat Base Camp.\n\nFairy Meadows is also rich in flora and fauna. During summer, the meadows are carpeted with wildflowers, and the surrounding forests are home to various bird species and occasional wildlife sightings.\n\nUnlike many high-altitude destinations in Pakistan, Fairy Meadows is accessible to a wider range of fitness levels. The relatively short approach and moderate altitude make it perfect for families and those new to high-altitude environments.\n\nWhether you're seeking a peaceful retreat in nature, a photography paradise, or a gentle introduction to the mountains of Pakistan, Fairy Meadows offers an unforgettable experience that lives up to its enchanting name.",
    },
]